.publish:
  stage: deploy
  image: node:16
  needs: 
    - test
  tags:
    - dind
  before_script:
    - npm set registry https://npm.lernetz.ch
    - echo '//npm.lernetz.ch/:_authToken=${NPM_TOKEN}'>.npmrc

test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.27.0-focal
  script:
    - npm ci
    - npm run test



common_publish:
  extends: .publish
  only:
    changes:
      - "common/**/*"  
  script:
    - npm -w common publish


translate_publish:
  extends: .publish
  only:
    changes:
      - "translate/**/*"  
  script:
    - npm -w translate publish


request_publish:
  extends: .publish
  only:
    changes:
      - "request/**/*"  
  script:
    - npm -w request publish