.publish:
  stage: deploy
  image: node
  needs: 
    - test
  tags:
    - dind
  before_script:
    - npm set registry https://npm.lernetz.ch
    - echo '//npm.lernetz.ch/:_authToken=${NPM_TOKEN}'>.npmrc

test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.28.1-focal
  cache:
    key:
      files:
        - package.json
        - package-lock.json
      prefix: "$CI_JOB_NAME"
    paths:
      - node_modules
  script:
    - npm i
    - npm run dev && npm run test


common_publish:
  extends: .publish
  rules:
    - changes: 
      - common/package.json
  script:
    - npm -w common publish


translate_publish:
  extends: .publish
  rules:
    - changes: 
      - translate/package.json
  script:
    - npm -w translate publish


request_publish:
  extends: .publish
  rules:
    - changes: 
      - request/package.json
  script:
    - npm -w request publish

embed_publish:
  extends: .publish
  rules:
    - changes: 
      - embed/package.json
  script:
    - npm -w embed publish