.publish:
  stage: build
  image: node:16
  tags:
    - dind
  before_script:
    - npm set registry https://npm.lernetz.ch
    - echo '//npm.lernetz.ch/:_authToken=${NPM_TOKEN}'>.npmrc


common_publish:
  extends: .publish
  #only:
  #  changes:
  #    - "common/**/*"  
  script:
    npm -w common publish